homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index }
    
staticpage:
    pattern:  /{page}/
    defaults: { _controller: FrontendBundle:Default:static }
    requirements:
        page: general|empresas|comunidades|aseguradoras|particulares|presupuestos|contacto|legal|acceso-usuarios